version: '3.7'

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    deploy:
      placement:
        constraints:
          - node.role == worker
 
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wp-content:/var/www/html/wp-content
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wpdb
    deploy:
      placement:
        constraints:
          - node.role == worker
volumes:
  mysql-data:
    driver: rexray
    driver_opts:
      size: 20
  wp-content:
    driver: rexray
    driver_opts:
      size: 20

